telekom/mltb2

.gitignore, mltb2/openai.py, pyproject.toml
=> Add OpenAI completion tools.

docs/source/api-reference/bs.rst, mltb2/bs.py, pyproject.toml, tests/test_bs.py
=> Add Beautiful Soup specific tools.

docs/source/conf.py, mltb2/data.py, mltb2/db.py, mltb2/md.py, mltb2/openai.py, mltb2/optuna.py, mltb2/plot.py, mltb2/somajo.py, pyproject.toml, tests/ori_data_loader.py, tests/test_md.py, tests/test_openai.py, tests/test_somajo.py, tests/test_somajo_transformers.py, tests/test_transformers.py
=> Update ruff config with "ALL" default.

pyproject.toml, tests/test_data.py
=> Add pytest-rerunfailures dependency and mark data tests as flaky.

mltb2/text.py, tests/test_text.py
=> Add XML tag detection function.

mltb2/arangodb.py
=> Add ArangoDB upload tool.

tests/test_openai.py
=> Add hypothesis tests for OpenAiTokenCounter class.

mltb2/openai.py, pyproject.toml, tests/test_openai.py
=> Add support for new OpenAI API.

pyproject.toml
=> Add pytest-random-order plugin and configure options.

mltb2/fasttext.py, tests/test_fasttext.py
=> Add default language for detection.

mltb2/text.py, tests/test_text.py
=> Add clean function `clean_all_invisible_chars_and_strip`.

Makefile, mltb2/files.py, pyproject.toml, tests/test_files.py, tests/test_md.py, tests/test_openai.py, tests/test_somajo.py, tests/test_somajo_transformers.py, tests/test_transformers.py
- tests
- file header
- README.md
- LICENSE file
=> Add FileBasedRestartableBatchDataProcessor.

mltb2/openai.py, tests/test_openai.py
- tests
- file header
- README.md
- LICENSE file
=> Add option to pass OpenAI key with os env.

mltb2/files.py, pyproject.toml, tests/test_files.py
- tests
- file header
- README.md
- LICENSE file
=> Fix unknown file issue in FileBasedRestartableBatchDataProcessor.

mltb2/files.py, pyproject.toml, tests/test_files.py
- tests
- file header
- README.md
- LICENSE file
=> Avoid duplicate results in FileBasedRestartableBatchDataProcessor.

mltb2/openai.py, pyproject.toml, tests/test_openai.py
- tests
- file header
- README.md
- LICENSE file
=> Add openai async function.

mltb2/files.py, tests/test_files.py
- tests
- file header
- README.md
- LICENSE file
=> Add len to FileBasedRestartableBatchDataProcessor

mltb2/files.py, pyproject.toml, tests/test_files.py
- tests
- file header
- README.md
- LICENSE file
=> Handle orphaned lock files for FileBasedRestartableBatchDataProcessor.

mltb2/openai.py, pyproject.toml, tests/test_openai.py
- tests
- file header
- README.md
- LICENSE file
=> Option for OpenAI special token removal.

.github/workflows/build_deploy_doc.yml, .github/workflows/mypy_check.yml, .github/workflows/pypi_upload.yml, .github/workflows/pytest.yml, .github/workflows/ruff_check.yml, .github/workflows/static_checks.yml, CONTRIBUTING.md, docs/source/conf.py, mltb2/arangodb.py, mltb2/bs.py, mltb2/data.py, mltb2/db.py, mltb2/fasttext.py, mltb2/files.py, mltb2/md.py, mltb2/openai.py, mltb2/plot.py, mltb2/somajo.py, mltb2/somajo_transformers.py, mltb2/text.py, mltb2/transformers.py, pyproject.toml, tests/ori_data_loader.py, tests/test_openai.py
- remove 3.8
- add 3.12
- tests
- file header
- README.md
- LICENSE file
=> Update Python Versions

mltb2/openai.py, pyproject.toml, tests/test_files.py
- tests
- file header
- README.md
- LICENSE file
=> Add option for `AzureMLOnBehalfOfCredential` for openai
